### ISSUE TITLE
Transfer learning error

### ISSUE THREAD

**Issue by panovr** [AndersonJo/pytorch-examples#1]
I run the "Transfer Learning" script on a custom dataset, but there is an error:
> Traceback (most recent call last):
>   File "incep.py", line 74, in <module>
>     train_model(inception, criterion, optimizer)
>   File "incep.py", line 64, in train_model
>     y_pred = inception(x_sample)
>   File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/torchvision/models/inception.py", line 74, in forward
>     x[1] = x[1] * (0.224 / 0.5) + (0.456 - 0.5) / 0.5
>   File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 69, in __getitem__
>     return Index(key)(self)
>   File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/tensor.py", line 16, in forward
>     result = i.index(self.index)
> IndexError: index 1 is out of range for dimension 0 (of size 1)

**Comment by dondon2475848** [comment]
I had same issue when i use inception model.

**Comment by AndersonJo** [comment]
It may be attributed to different version of torchvision. 
When I look into torchvision/models/inception.py line 74, there is no something like 
```
"x[1] = x[1] * (0.224 / 0.5) + (0.456 - 0.5) / 0.5"
```

instead line 74  is.. 
```
x[:, 1] = x[:, 1] * (0.224 / 0.5) + (0.456 - 0.5) / 0.5
```

So the code is different. 
The solution to this problem is to upgrade torchvision library. 

I close the issue.

**Comment by dondon2475848** [comment]
@AndersonJo Thank you for your kind help!
My old torchvision  version is torchvision-0.1.8
The latest version is 0.1.9
I upgrade torchvision library using the following code:
`pip install --upgrade torchvision`

**Comment by panovr** [comment]
I can validate the error is caused by the old version of torchvision.
